def run():
  print("            ___     ")
  print("           |_ _|    ")
  print("          ((O O))   ")
  print('          _|\_/|_   ')
  print('         / \___/ \  ')
  print('        /  /   \  \ ')
  print('          |     |   ')
  print('          |     |   ')
  print('Please enter a character for the eye')
  o = input()
  print("            ___     ")
  print("           |_ _|    ")
  print("          (({} {}))   ".format(o, o))
  print('          _|\_/|_   ')
  print('         / \___/ \  ')
  print('        /  /   \  \ ')
  print('          |     |   ')
  print('          |     |   ')