print('How many mountains should I display?')
response = int(input())
print()
print('Displaying...')
print()
for count in range(0, response, 1):

  print('      __ ')
  print('     /  \_  ')
  print('    /^    \\')
  print('   /  ^    \_ ')
  print(' _/ ^ ^     ^\ ')
  print(' /  ^     ^    \\')
print()
print('Done!', end="")